apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
type: Opaque
data:
  grafana-username: cm9vdA== # this is taken by running echo -n root | base64
  grafana-password: c2VjcmV0 # this is taken by running echo -n secret | base64


